//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

enum TokenType {
  ADD = 'add',
  ASSIGN = 'assign',
  COLON = 'colon',
  COMMA = 'comma',
  DIV = 'div',
  DOT = 'dot',
  EQ = 'eq',
  FLOORDIV = 'floordiv',
  GT = 'gt',
  GTEQ = 'gteq',
  LBRACE = 'lbrace',
  LBRACKET = 'lbracket',
  LPAREN = 'lparen',
  LT = 'lt',
  LTEQ = 'lteq',
  MOD = 'mod',
  MUL = 'mul',
  NE = 'ne',
  PIPE = 'pipe',
  POW = 'pow',
  RBRACE = 'rbrace',
  RBRACKET = 'rbracket',
  RPAREN = 'rparen',
  SEMICOLON = 'semicolon',
  SUB = 'sub',
  TILDE = 'tilde',
  WHITESPACE = 'whitespace',
  FLOAT = 'float',
  INTEGER = 'integer',
  NAME = 'name',
  STRING = 'string',
  OPERATOR = 'operator',
  BLOCK_BEGIN = 'block_begin',
  BLOCK_END = 'block_end',
  VARIABLE_BEGIN = 'variable_begin',
  VARIABLE_END = 'variable_end',
  RAW_BEGIN = 'raw_begin',
  RAW_END = 'raw_end',
  COMMENT_BEGIN = 'comment_begin',
  COMMENT_END = 'comment_end',
  COMMENT = 'comment',
  LINESTATEMENT_BEGIN = 'linestatement_begin',
  LINESTATEMENT_END = 'linestatement_end',
  LINECOMMENT_BEGIN = 'linecomment_begin',
  LINECOMMENT_END = 'linecomment_end',
  LINECOMMENT = 'linecomment',
  DATA = 'data',
  INITIAL = 'initial',
  EOS = 'eos',
  UNKNOWN = 'unknown',
}

export {
  TokenType,
}