//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const fgChart = [
  {
    key: 'fg-chart-1',
    useBorder: false,
    token: 'COZ_fg_color_orange',
    origin: 'COZColorYellow5',
    variable: 'coz-fg-color-orange',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-2',
    useBorder: false,
    token: 'COZ_fg_color_orange_dim',
    origin: 'COZColorYellow3',
    variable: 'coz-fg-color-orange-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-3',
    useBorder: false,
    token: 'COZ_fg_color_emerald',
    origin: 'COZColorGreen5',
    variable: 'coz-fg-color-emerald',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-4',
    useBorder: false,
    token: 'COZ_fg_color_emerald_dim',
    origin: 'COZColorGreen3',
    variable: 'coz-fg-color-emerald-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-5',
    useBorder: false,
    token: 'COZ_fg_color_cyan',
    origin: 'COZColorCyan50',
    variable: 'coz-fg-color-cyan',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-6',
    useBorder: false,
    token: 'COZ_fg_color_cyan_dim',
    origin: 'COZColorCyan30',
    variable: 'coz-fg-color-cyan-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-7',
    useBorder: false,
    token: 'COZ_fg_color_blue',
    origin: 'COZColorBlue50',
    variable: 'coz-fg-color-blue',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-8',
    useBorder: false,
    token: 'COZ_fg_color_blue_dim',
    origin: 'COZColorBlue30',
    variable: 'coz-fg-color-blue-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-9',
    useBorder: false,
    token: 'COZ_fg_color_purple',
    origin: 'COZColorPurple50',
    variable: 'coz-fg-color-purple',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-10',
    useBorder: false,
    token: 'COZ_fg_color_purple_dim',
    origin: 'COZColorPurple30',
    variable: 'coz-fg-color-purple-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-11',
    useBorder: false,
    token: 'COZ_fg_color_magenta',
    origin: 'COZColorMagenta50',
    variable: 'coz-fg-color-magenta',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-12',
    useBorder: false,
    token: 'COZ_fg_color_magenta_dim',
    origin: 'COZColorMagenta30',
    variable: 'coz-fg-color-magenta-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-chart-13',
    useBorder: false,
    token: 'COZ_fg_color_yellow',
    origin: 'COZColorYellow50',
    variable: 'coz-fg-color-yellow',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-chart-14',
    useBorder: false,
    token: 'COZ_fg_color_yellow_dim',
    origin: 'COZColorYellow30',
    variable: 'coz-fg-color-yellow-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
];
