//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const fgCode = [
  {
    key: 'fg-code-1',
    useBorder: false,
    token: 'COZ_fg_hglt_orange',
    origin: 'COZColorOrange5',
    variable: 'coz-fg-hglt-orange',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-2',
    useBorder: false,
    token: 'COZ_fg_hglt_orange_dim',
    origin: 'COZColorOrange3',
    variable: 'coz-fg-hglt-orange-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-code-3',
    useBorder: false,
    token: 'COZ_fg_hglt_emerald',
    origin: 'COZColorEmerald5',
    variable: 'coz-fg-hglt-emerald',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-4',
    useBorder: false,
    token: 'COZ_fg_hglt_emerald_dim',
    origin: 'COZColorGreen3',
    variable: 'coz-fg-hglt-emerald-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-code-5',
    useBorder: false,
    token: 'COZ_fg_hglt_cyan',
    origin: 'COZColorCyan5',
    variable: 'coz-fg-hglt-cyan',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-6',
    useBorder: false,
    token: 'COZ_fg_hglt_cyan_dim',
    origin: 'COZColorCyan3',
    variable: 'coz-fg-hglt-cyan-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-code-7',
    useBorder: false,
    token: 'COZ_fg_hglt_blue',
    origin: 'COZColorBlue5',
    variable: 'coz-fg-hglt-blue',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-8',
    useBorder: false,
    token: 'COZ_fg_hglt_blue_dim',
    origin: 'COZColorBlue3',
    variable: 'coz-fg-hglt-blue-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-code-9',
    useBorder: false,
    token: 'COZ_fg_hglt_purple',
    origin: 'COZColorPurple5',
    variable: 'coz-fg-hglt-purple',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-10',
    useBorder: false,
    token: 'COZ_fg_hglt_purple_dim',
    origin: 'COZColorPurple3',
    variable: 'coz-fg-hglt-purple-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
  {
    key: 'fg-code-11',
    useBorder: false,
    token: 'COZ_fg_hglt_magenta',
    origin: 'COZColorMagenta5',
    variable: 'coz-fg-hglt-magenta',
    useAge: '半透明彩色底文字',
  },
  {
    key: 'fg-code-12',
    useBorder: false,
    token: 'COZ_fg_hglt_magenta_dim',
    origin: 'COZColorMagenta3',
    variable: 'coz-fg-hglt-magenta-dim',
    useAge: '半透明彩色底文字 (disabled)',
  },
];
