//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const fgThemes = [
  {
    key: 'fg-theme-1',
    useBorder: true,
    token: 'COZ_fg_hglt_plus',
    origin: 'COZColorFgInvert',
    variable: 'coz-fg-hglt-plus',
    useAge: '高亮+，多用于实色彩色背景底下的文字色（按钮字体色）',
  },
  {
    key: 'fg-theme-2',
    useBorder: true,
    token: 'COZ_fg_hglt_plus_dim',
    origin: 'COZColorFgInvert',
    variable: 'coz-fg-hglt-plus-dim',
    useAge: '高亮 + 置灰，多用于实色彩色底文字 (disabled 字体色)',
  },
  {
    key: 'fg-theme-3',
    useBorder: false,
    token: 'COZ_fg_hglt',
    origin: 'COZColorBrand5',
    variable: 'coz-fg-hglt',
    useAge: '高亮，半透明彩色底文字（按钮字体色）',
  },
  {
    key: 'fg-theme-4',
    useBorder: false,
    token: 'COZ_fg_hglt_dim',
    origin: 'COZColorBrand3',
    variable: 'coz-fg-hglt-dim',
    useAge: '半透明彩色底文字 (disabled 字体色)',
  },
  {
    key: 'fg-theme-5',
    useBorder: false,
    token: 'COZ_fg_hglt_ai',
    origin: 'COZColorPurple5',
    variable: 'coz-fg-hglt-ai',
    useAge: 'AIButton 字体色',
  },
  {
    key: 'fg-theme-6',
    useBorder: false,
    token: 'COZ_fg_hglt_ai_dim',
    origin: 'COZColorPurple3',
    variable: 'coz-fg-hglt-ai-dim',
    useAge: 'AIButton 字体色 (disabled)',
  },
  {
    key: 'fg-theme-7',
    useBorder: false,
    token: 'COZ_fg_plus',
    origin: 'COZColorFg4',
    variable: 'coz-fg-plus',
    useAge: '强，高亮着重文字 (导航栏文字)',
  },
  {
    key: 'fg-theme-8',
    useBorder: false,
    token: 'COZ_fg_primary',
    origin: 'COZColorFg3',
    variable: 'coz-fg-primary',
    useAge: '默认，文字色 (正文文字色)',
  },
  {
    key: '9',
    useBorder: false,
    token: 'COZ_fg_secondary',
    origin: 'COZColorFg2',
    variable: 'coz-fg-secondary',
    useAge: '弱，文字色 (说明文字色)',
  },
  {
    key: 'fg-theme-10',
    useBorder: false,
    token: 'COZ_fg_dim',
    origin: 'COZColorFg1',
    variable: 'coz-fg-dim',
    useAge: '置灰，占位文字、文字 (disabled）',
  },
  {
    key: 'fg-theme-11',
    useBorder: true,
    token: 'COZ_fg_dim_white',
    origin: 'COZColorFgWhite',
    variable: 'coz-fg-white',
    useAge: '深浅模式下均为白色（开关）',
  },
  {
    key: 'fg-theme-12',
    useBorder: true,
    token: 'COZ_fg_white_dim',
    origin: 'COZColorFgWhite',
    variable: 'coz-fg-white-dim',
    useAge: '深浅模式下均为白色（开关）',
  },
];
