//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const mgCard = [
  {
    key: 'mg-card-1',
    token: 'COZ_mg_color_plus_orange',
    origin: 'COZColorYellow5',
    variable: 'coz-mg-color-plus-orange',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-2',
    token: 'COZ_mg_color_plus_emerald',
    origin: 'COZColorGreen5',
    variable: 'coz-mg-color-plus-emerald',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-3',
    token: 'COZ_mg_color_plus_cyan',
    origin: 'COZColorCyan50',
    variable: 'coz-mg-color-plus-cyan',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-4',
    token: 'COZ_mg_color_plus_blue',
    origin: 'COZColorBlue50',
    variable: 'coz-mg-color-plus-blue',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-5',
    token: 'COZ_mg_color_plus_purple',
    origin: 'COZColorPurple50',
    variable: 'coz-mg-color-plus-purple',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-6',
    token: 'COZ_mg_color_plus_magenta',
    origin: 'COZColorMagenta50',
    variable: 'coz-mg-color-plus-magenta',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-7',
    token: 'COZ_mg_color_plus_yellow',
    origin: 'COZColorYellow50',
    variable: 'coz-mg-color-plus-yellow',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-8-0',
    token: 'COZ_mg_color_orange',
    origin: 'COZColorYellow1',
    variable: 'coz-mg-color-orange',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-8',
    token: 'COZ_mg_color_orange_pressed',
    origin: 'COZColorYellow3',
    variable: 'coz-mg-color-orange-pressed',
    useAge: '默认高亮色（头像、标签等 pressed）',
  },
  {
    key: 'mg-card-9',
    token: 'COZ_mg_color_orange_hovered',
    origin: 'COZColorYellow2',
    variable: 'coz-mg-color-orange-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-10',
    token: 'COZ_mg_color_emerald_pressed',
    origin: 'COZColorGreen3',
    variable: 'coz-mg-color-emerald-pressed',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-11',
    token: 'COZ_mg_color_emerald_hovered',
    origin: 'COZColorGreen2',
    variable: 'coz-mg-color-emerald-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-12',
    token: 'COZ_mg_color_emerald',
    origin: 'COZColorGreen1',
    variable: 'coz-mg-color-emerald',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-13',
    token: 'COZ_mg_color_cyan_pressed',
    origin: 'COZColorCyan30',
    variable: 'coz-mg-color-cyan-pressed',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-14',
    token: 'COZ_mg_color_cyan_hovered',
    origin: 'COZColorCyan20',
    variable: 'coz-mg-color-cyan-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-15',
    token: 'COZ_mg_color_cyan',
    origin: 'COZColorCyan10',
    variable: 'coz-mg-color-cyan',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-16',
    token: 'COZ_mg_color_blue_pressed',
    origin: 'COZColorBlue30',
    variable: 'coz-mg-color-blue-pressed',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-17',
    token: 'COZ_mg_color_blue_hovered',
    origin: 'COZColorBlue20',
    variable: 'coz-mg-color-blue-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-18',
    token: 'COZ_mg_color_blue',
    origin: 'COZColorBlue10',
    variable: 'coz-mg-color-blue',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-19',
    token: 'COZ_mg_color_purple_pressed',
    origin: 'COZColorPurple30',
    variable: 'coz-mg-color-purple-pressed',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-20',
    token: 'COZ_mg_color_purple_hovered',
    origin: 'COZColorPurple20',
    variable: 'coz-mg-color-purple-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-21',
    token: 'COZ_mg_color_purple',
    origin: 'COZColorPurple10',
    variable: 'coz-mg-color-purple',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-22',
    token: 'COZ_mg_color_magenta_pressed',
    origin: 'COZColorMagenta30',
    variable: 'coz-mg-color-magenta-pressed',
    useAge: '默认高亮色+（头像、标签等）',
  },
  {
    key: 'mg-card-23',
    token: 'COZ_mg_color_magenta_hovered',
    origin: 'COZColorMagenta20',
    variable: 'coz-mg-color-magenta-hovered',
    useAge: '默认高亮色（头像、标签等 hovered）',
  },
  {
    key: 'mg-card-24',
    token: 'COZ_mg_color_magenta',
    origin: 'COZColorMagenta10',
    variable: 'coz-mg-color-magenta',
    useAge: '默认高亮色（头像、标签等）',
  },
  {
    key: 'mg-card-25',
    useBorder: true,
    token: 'COZ_mg_card_pressed',
    origin: 'COZColorBg3',
    variable: 'coz-mg-card',
    useAge: '默认白底色（Card 卡片）',
  },
  {
    key: 'mg-card-26',
    useBorder: true,
    token: 'COZ_mg_card_hovered',
    origin: 'COZColorBg3',
    variable: 'coz-mg-card-hovered',
    useAge: '默认白底色（Card 卡片）',
  },
  {
    key: 'mg-card-27',
    useBorder: true,
    token: 'COZ_mg_card',
    origin: 'COZColorBg3',
    variable: 'coz-mg-card',
    useAge: '默认白底色（Card 卡片）',
  },
  {
    key: 'mg-card-28',
    useBorder: true,
    token: 'COZ_mg_color_plus_brand',
    origin: 'COZColorBrand50',
    variable: 'coz-mg-color-plus-brand',
    useAge: 'branding品牌元素专用',
  },
];
