//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const mgThemes = [
  {
    key: 'mg-themes-1',
    token: 'COZ_mg_hglt_secondary_pressed',
    origin: 'COZColorBrand2',
    variable: 'coz-mg-hglt-secondary-pressed',
    useAge: '默认 pressed（小原素 pressed 高亮背景色）',
  },
  {
    key: 'mg-themes-2',
    token: 'COZ_mg_hglt_secondary_hovered',
    origin: 'COZColorBrand1',
    variable: 'coz-mg-hglt-secondary-hovered',
    useAge: '默认 hovered（小原素 hovered 高亮背景色）',
  },
  {
    key: 'mg-themes-3',
    token: 'COZ_mg_hglt_secondary',
    origin: 'COZColorBrand0',
    variable: 'coz-mg-hglt-secondary',
    useAge: '默认（高亮弱等）',
  },
  {
    key: 'mg-themes-4',
    token: 'COZ_mg_plus_pressed',
    origin: 'COZColorBg8',
    variable: 'coz-mg-plus-pressed',
    useAge: '默认 pressed（小原素 pressed 加强背景色）',
  },
  {
    key: 'mg-themes-5',
    token: 'COZ_mg_plus_hover',
    origin: 'COZColorBg7',
    variable: 'coz-mg-plus-hovered',
    useAge: '默认 hovered（小原素 hovered 加强背景色）',
  },
  {
    key: 'mg-themes-6',
    token: 'COZ_mg_plus',
    origin: 'COZColorBg6',
    variable: 'coz-mg-plus',
    useAge: '默认（按钮、标签等）',
  },
  {
    key: 'mg-themes-7',
    token: 'COZ_mg_primary_pressed',
    origin: 'COZColorBg7',
    variable: 'coz-mg-primary-pressed',
    useAge: '默认 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-themes-8',
    token: 'COZ_mg_primary_hovered',
    origin: 'COZColorBg6',
    variable: 'coz-mg-primary-hovered',
    useAge: '默认 pressed（小原素 hovered 背景色）',
  },
  {
    key: 'mg-themes-9',
    token: 'COZ_mg_primary',
    origin: 'COZColorBg5',
    variable: 'coz-mg-primary',
    useAge: '默认（按钮、标签等）',
  },
  {
    key: 'mg-themes-10',
    token: 'COZ_mg_secondary_pressed',
    origin: 'COZColorBg6',
    variable: 'coz-mg-secondary-pressed',
    useAge: '弱 pressed（大原素、透明底原素 pressed）',
  },
  {
    key: 'mg-themes-11',
    token: 'COZ_mg_secondary_hovered',
    origin: 'COZColorBg5',
    variable: 'coz-mg-secondary-hovered',
    useAge: '弱 hovered（大原素、透明底原素 hovered）',
  },
  {
    key: 'mg-themes-12',
    token: 'COZ_mg_secondary',
    origin: 'COZColorBg4',
    variable: 'coz-mg-secondary',
    useAge: '弱 hovered（大原素、透明底原素 hovered）',
  },
  {
    key: 'mg-themes-13',
    token: 'COZ_mg_mask',
    origin: 'COZColorMask5',
    variable: 'coz-mg-mask',
    useAge: '弹窗蒙层（深浅模式均为黑色）',
  },
  {
    key: 'mg-themes-14',
    token: 'COZ_mg_hglt_plus_pressed',
    origin: 'COZColorBrand7',
    variable: 'coz-mg-hglt-plus-pressed',
    useAge: '高亮 + pressed（按钮 pressed 背景色）',
  },
  {
    key: 'mg-themes-15',
    token: 'COZ_mg_hglt_plus_hovered',
    origin: 'COZColorBrand6',
    variable: 'coz-mg-hglt-plus-hovered',
    useAge: '高亮 + hovered（按钮 hovered 背景色）',
  },
  {
    key: 'mg-themes-16',
    token: 'COZ_mg_hglt_plus',
    origin: 'COZColorBrand5',
    variable: 'coz-mg-hglt-plus',
    useAge: '高亮 + 小元素（按钮、标签等）',
  },
  {
    key: 'mg-themes-17',
    token: 'COZ_mg_hglt_plus_dim',
    origin: 'COZColorBrand3',
    variable: 'coz-mg-hglt-plus-dim',
    useAge: '高亮 + 小元素（按钮、标签 disabled）',
  },
  {
    key: 'mg-themes-18',
    token: 'COZ_mg_hglt_plus_ai_pressed',
    origin: 'COZColorBrand5',
    variable: 'coz-mg-hglt-plus-ai-pressed',
    useAge: '高亮 + 小元素（按钮、标签等）',
  },
  {
    key: 'mg-themes-19',
    token: 'COZ_mg_hglt_plus_ai_hovered',
    origin: 'COZColorPurple6',
    variable: 'coz-mg-hglt-plus-ai-hovered',
    useAge: '高亮 + 小元素（按钮、标签 disabled）',
  },
  {
    key: 'mg-themes-20',
    token: 'COZ_mg_hglt_plus_ai',
    origin: 'COZColorPurple5',
    variable: 'coz-mg-hglt-plus-ai',
    useAge: '高亮 + 小元素（按钮、标签等）',
  },
  {
    key: 'mg-themes-21',
    token: 'COZ_mg_hglt_plus_ai_dim',
    origin: 'COZColorPurple3',
    variable: 'coz-mg-hglt-plus-ai-dim',
    useAge: '高亮 + 小元素（按钮、标签 disabled）',
  },
  {
    key: 'mg-themes-22',
    token: 'COZ_mg_hglt_pressed',
    origin: 'COZColorBrand3',
    variable: 'coz-mg-hglt-pressed',
    useAge: '高亮 + 小元素（按钮、标签等 pressed）',
  },
  {
    key: 'mg-themes-23',
    token: 'COZ_mg_hglt_hovered',
    origin: 'COZColorBrand2',
    variable: 'coz-mg-hglt-hovered',
    useAge: '高亮 + 小元素（按钮、标签等 pressed）',
  },
  {
    key: 'mg-themes-24',
    token: 'COZ_mg_hglt',
    origin: 'COZColorBrand1',
    variable: 'coz-mg-hglt',
    useAge: '高亮 + 小元素（按钮、标签等）',
  },
  {
    key: 'mg-themes-25',
    token: 'COZ_mg_hglt_ai_pressed',
    origin: 'COZColorPurple3',
    variable: 'coz-mg-hglt-ai-pressed',
    useAge: '高亮 + 小元素（按钮、标签等 pressed）',
  },
  {
    key: 'mg-themes-26',
    token: 'COZ_mg_hglt_ai_hovered',
    origin: 'COZColorPurple2',
    variable: 'coz-mg-hglt-ai-hovered',
    useAge: '高亮 + 小元素（按钮、标签等 hovered）',
  },
  {
    key: 'mg-themes-27',
    token: 'COZ_mg_hglt_ai',
    origin: 'COZColorPurple1',
    variable: 'coz-mg-hglt-ai',
    useAge: '高亮 + 小元素（按钮、标签等）',
  },
  {
    key: 'mg-themes-28',
    token: 'COZ_mg_hglt_secondary_red',
    origin: 'COZColorRed0',
    variable: 'coz-mg-hglt-secondary-red',
    useAge: '默认（高亮弱等）',
  },
  {
    key: 'mg-themes-29',
    token: 'COZ_mg_hglt_secondary_yellow',
    origin: 'COZColorYellow0',
    variable: 'coz-mg-hglt-secondary-yellow',
    useAge: '默认（高亮弱等）',
  },
  {
    key: 'mg-themes-30',
    token: 'COZ_mg_hglt_secondary_green',
    origin: 'COZColorRed0',
    variable: 'coz-mg-hglt-secondary-green',
    useAge: '默认（高亮弱等）',
  },
];
