//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const mgFunctional = [
  {
    key: 'mg-functional-1',
    token: 'COZ_mg_hglt_plus_red_pressed',
    origin: 'COZColorRed7',
    variable: 'coz-mg-hglt-plus-red-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-2',
    token: 'COZ_mg_hglt_plus_red_hovered',
    origin: 'COZColorRed6',
    variable: 'coz-mg-hglt-plus-red-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-3',
    token: 'COZ_mg_hglt_plus_red',
    origin: 'COZColorRed5',
    variable: 'coz-mg-hglt-plus-red',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
  {
    key: 'mg-functional-4',
    token: 'COZ_mg_hglt_plus_red_dim',
    origin: 'COZColorRed3',
    variable: 'coz-mg-hglt-plus-red-dim',
    useAge: '高亮 disabled（小原素 disabled 背景色）',
  },
  {
    key: 'mg-functional-5',
    token: 'COZ_mg_hglt_plus_yellow_pressed',
    origin: 'COZColorYellow7',
    variable: 'coz-mg-hglt-plus-yellow-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-6',
    token: 'COZ_mg_hglt_plus_yellow_hovered',
    origin: 'COZColorYellow6',
    variable: 'coz-mg-hglt-plus-yellow-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-7',
    token: 'COZ_mg_hglt_plus_yellow',
    origin: 'COZColorYellow5',
    variable: 'coz-mg-hglt-plus-yellow',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
  {
    key: 'mg-functional-8',
    token: 'COZ_mg_hglt_plus_yellow_dim',
    origin: 'COZColorYellow3',
    variable: 'coz-mg-hglt-plus-yellow-dim',
    useAge: '高亮 disabled（小原素 disabled 背景色）',
  },
  {
    key: 'mg-functional-9',
    token: 'COZ_mg_hglt_plus_green_pressed',
    origin: 'COZColorGreen7',
    variable: 'coz-mg-hglt-plus-green-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-10',
    token: 'COZ_mg_hglt_plus_ygreen_hovered',
    origin: 'COZColorGreen6',
    variable: 'coz-mg-hglt-plus-green-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-11',
    token: 'COZ_mg_hglt_plus_green',
    origin: 'COZColorGreen5',
    variable: 'coz-mg-hglt-plus-green',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
  {
    key: 'mg-functional-12',
    token: 'COZ_mg_hglt_plus_green_dim',
    origin: 'COZColorGreen3',
    variable: 'coz-mg-hglt-plus-green-dim',
    useAge: '高亮 disabled（小原素 disabled 背景色）',
  },
  {
    key: 'mg-functional-13',
    token: 'COZ_mg_hglt_red_pressed',
    origin: 'COZColorRed3',
    variable: 'coz-mg-hglt-red-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-14',
    token: 'COZ_mg_hglt_red_hovered',
    origin: 'COZColorRed2',
    variable: 'coz-mg-hglt-red-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-15',
    token: 'COZ_mg_hglt_red',
    origin: 'COZColorRed1',
    variable: 'coz-mg-hglt-red',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
  {
    key: 'mg-functional-16',
    token: 'COZ_mg_hglt_yellow_pressed',
    origin: 'COZColorYellow3',
    variable: 'coz-mg-hglt-yellow-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-17',
    token: 'COZ_mg_hglt_yellow_hovered',
    origin: 'COZColorYellow2',
    variable: 'coz-mg-hglt-yellow-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-18',
    token: 'COZ_mg_hglt_yellow',
    origin: 'COZColorYellow1',
    variable: 'coz-mg-hglt-yellow',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
  {
    key: 'mg-functional-19',
    token: 'COZ_mg_hglt_green_pressed',
    origin: 'COZColorGreen3',
    variable: 'coz-mg-hglt-green-pressed',
    useAge: '高亮 pressed（小原素 pressed 背景色）',
  },
  {
    key: 'mg-functional-20',
    token: 'COZ_mg_hglt_green_hovered',
    origin: 'COZColorGreen2',
    variable: 'coz-mg-hglt-green-hovered',
    useAge: '高亮 hovered（小原素 hovered 背景色）',
  },
  {
    key: 'mg-functional-21',
    token: 'COZ_mg_hglt_green',
    origin: 'COZColorGreen1',
    variable: 'coz-mg-hglt-green',
    useAge: '高亮 normal（小原素 normal 背景色）',
  },
];
