//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

export const strokeThemes = [
  {
    key: 'stroke-themes-1',
    token: 'COZ_stroke_plus',
    origin: 'COZColorStroke6',
    variable: 'coz-stroke-plus',
    useAge: '强（输入框类组件边框）',
  },
  {
    key: 'stroke-themes-2',
    token: 'COZ_stroke_primary',
    origin: 'COZColorStroke5',
    variable: 'coz-stroke-primary',
    useAge: '默认（分界线、分割线）',
  },
  {
    key: 'stroke-themes-3',
    token: 'COZ_stroke_hglt',
    origin: 'COZColorBrand5',
    variable: 'coz-stroke-hglt',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-4',
    token: 'COZ_stroke_hglt_red',
    origin: 'COZColorRed5',
    variable: 'coz-stroke-hglt-red',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-5',
    token: 'COZ_stroke_hglt_yellow',
    origin: 'COZColorYellow5',
    variable: 'coz-stroke-hglt-yellow',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-6',
    token: 'COZ_stroke_hglt_green',
    origin: 'COZColorGreen5',
    variable: 'coz-stroke-hglt-green',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-7',
    token: 'COZ_stroke_hglt_orange',
    origin: 'COZColorOrange5',
    variable: 'coz-stroke-color-orange',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-8',
    token: 'COZ_stroke_hglt_emerald',
    origin: 'COZColorGreen5',
    variable: 'coz-stroke-color-emerald',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-9',
    token: 'COZ_stroke_color_cyan',
    origin: 'COZColorCyan50',
    variable: 'coz-stroke-color-cyan',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-10',
    token: 'COZ_stroke_color_blue',
    origin: 'COZColorBlue50',
    variable: 'coz-stroke-color-blue',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-11',
    token: 'COZ_stroke_color_purple',
    origin: 'COZColorBlue50',
    variable: 'coz-stroke-color-purple',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-12',
    token: 'COZ_stroke_color_magenta',
    origin: 'COZColorMagenta50',
    variable: 'coz-stroke-color-magenta',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-13',
    token: 'COZ_stroke_color_yellow',
    origin: 'COZColorYellow50',
    variable: 'coz-stroke-color-yellow',
    useAge: '高亮（弹窗浮层（导航栏）、卡片/面板）',
  },
  {
    key: 'stroke-themes-14',
    token: 'COZ_stroke_color_brand',
    origin: 'COZColorBrand50',
    variable: 'coz-stroke-color-brand',
    useAge: '高亮（branding 品牌原素专用）',
  },
];
