//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  stringContentSingleQuote = 30,
  stringEndSingleQuote = 31,
  stringContentDoubleQuote = 32,
  stringEndDoubleQuote = 33,
  JinjaExpressionEnd = 1,
  JinjaStatementEnd = 2,
  JinjaCommentEnd = 3,
  RawText = 4,
  JinjaText = 5,
  JinjaProgram = 6,
  JinjaComment = 7,
  JinjaCommentStart = 8,
  JinjaCommentContent = 9,
  JinjaExpression = 10,
  JinjaExpressionStart = 11,
  JinjaKeyword = 23,
  JinjaIdentifier = 13,
  JinjaStringLiteral = 14,
  JinjaNumberLiteral = 15,
  JinjaFilterName = 16,
  JinjaExpressionUnknownContent = 17,
  JinjaRawBlock = 18,
  JinjaRawOpenStatement = 19,
  JinjaStatementStart = 20,
  JinjaRawCloseStatement = 22,
  JinjaStatement = 24
