//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlight} from "./highlight.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QVOPOOO_QQO'#C^OOOO'#Cc'#CcQVOPOOOOQO'#Cd'#CdOgQQO,58xOOOO,58x,58xOOOO-E6a-E6aOOQO-E6b-E6bOOOO1G.d1G.d",
  stateData: "r~OZOS~ORPOUQO~OSSOTUO~OSSOTXO~OZS~",
  goto: "jXPPYPPPP^dTQORQRORVRQTPRWT",
  nodeNames: "⚠ Template Interpolation {{ InterpolationContent }} Text",
  maxTerm: 11,
  nodeProps: [
    ["closedBy", 3,"InterpolationEnd"],
    ["openedBy", 5,"InterpolationOpen"]
  ],
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "+hRRkOX!vX^'Y^p!vpq'Yq#o!v#o#p)W#p#q!v#q#r*`#r#y!v#y#z'Y#z$f!v$f$g'Y$g#BY!v#BY#BZ'Y#BZ$IS!v$IS$I_'Y$I_$I|!v$I|$JO'Y$JO$JT!v$JT$JU'Y$JU$KV!v$KV$KW'Y$KW&FU!v&FU&FV'Y&FV;'S!v;'S;=`'S<%lO!vR!}VUPSQO#o!v#o#p#d#p#q!v#q#r%[#r;'S!v;'S;=`'S<%lO!vR#iXSQO#o!v#o#p$U#p#q!v#q#r%[#r;'S!v;'S;=`'S<%l~!v~O!v~~&}Q$ZTSQO#q$U#q#r$j#r;'S$U;'S;=`%P<%lO$UQ$mUO#q$U#r;'S$U;'S;=`%P<%l~$U~O$U~~%VQ%SP;=`<%l$UQ%[OSQR%aXUPO#o!v#o#p#d#p#q!v#q#r%|#r;'S!v;'S;=`'S<%l~!v~O!v~~%VP&RTUPO#o%|#o#p&b#p;'S%|;'S;=`&w<%lO%|P&eUO#o%|#p;'S%|;'S;=`&w<%l~%|~O%|~~&}P&zP;=`<%l%|P'SOUPR'VP;=`<%l!vR'ckUPZQSQOX!vX^'Y^p!vpq'Yq#o!v#o#p#d#p#q!v#q#r%[#r#y!v#y#z'Y#z$f!v$f$g'Y$g#BY!v#BY#BZ'Y#BZ$IS!v$IS$I_'Y$I_$I|!v$I|$JO'Y$JO$JT!v$JT$JU'Y$JU$KV!v$KV$KW'Y$KW&FU!v&FU&FV'Y&FV;'S!v;'S;=`'S<%lO!vR)]XSQO#o!v#o#p)x#p#q!v#q#r%[#r;'S!v;'S;=`'S<%l~!v~O!v~~&}R*PTRPSQO#q$U#q#r$j#r;'S$U;'S;=`%P<%lO$UR*eXUPO#o!v#o#p#d#p#q!v#q#r+Q#r;'S!v;'S;=`'S<%l~!v~O!v~~%VR+XTTQUPO#o%|#o#p&b#p;'S%|;'S;=`&w<%lO%|",
  tokenizers: [0, 1],
  topRules: {"Template":[0,1]},
  tokenPrec: 31
})
