//  Copyright (c) 2025 coze-dev
//  SPDX-License-Identifier: MIT

// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  Interpolation = 2,
  InterpolationOpen = 3,
  InterpolationContent = 4,
  InterpolationEnd = 5,
  Text = 6
