name: Auto Tag on PR Merge

on:
  push:
    branches:
      - main
    paths:
      - '**/package.json'

permissions:
  contents: write

jobs:
  create-tag:
    strategy:
      matrix:
        include:
          - NodeVersion: 20.14.x
            NodeVersionDisplayName: 20
            OS: ubuntu-latest
    name: Node.js v${{ matrix.NodeVersionDisplayName }} (${{ matrix.OS }})
    runs-on: ubuntu-latest
    if: github.repository == 'coze-dev/rush-arch'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Config Git User
        run: |
          git config --local user.name "tecvan"
          git config --local user.email "tecvan.fe@gmail.com"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Version Change and Create Tag
        id: check_version
        run: |
          # 创建一个JSON数组来保存标签信息
          echo "tags_json=[]" >> $GITHUB_OUTPUT

          # 标记是否找到变更
          HAS_CHANGES=false

          # 找出所有修改过的package.json文件
          CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD | grep package.json)

          # 对每个修改的package.json文件检查版本是否变更
          for PKG_FILE in $CHANGED_PACKAGES; do
            # 获取当前版本
            CURRENT_VERSION=$(cat $PKG_FILE | jq -r '.version')

            # 获取之前的版本
            PREVIOUS_VERSION=$(git show HEAD^:$PKG_FILE 2>/dev/null | jq -r '.version' 2>/dev/null)

            # 如果版本发生变化，则创建标签
            if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
              PKG_NAME=$(cat $PKG_FILE | jq -r '.name')
              TAG_NAME="v/${PKG_NAME}@${CURRENT_VERSION}"

              echo "Version changed for $PKG_NAME: $PREVIOUS_VERSION -> $CURRENT_VERSION"
              echo "Creating tag: $TAG_NAME"

              git tag -a "$TAG_NAME" -m "Release $PKG_NAME@$CURRENT_VERSION"

              # 将此标签添加到输出数组
              tags_json=$(echo $tags_json | jq -c --arg tag "$TAG_NAME" '. += [$tag]')
              HAS_CHANGES=true
            fi
          done

          # 输出标签JSON和变更状态
          echo "tags_json=$tags_json" >> $GITHUB_OUTPUT
          echo "has_changes=$HAS_CHANGES" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'

      - name: Cache
        if: steps.check_version.outputs.has_changes == 'true'
        uses: actions/cache@v4
        with:
          path: |
            common/temp/pnpm-local
            common/temp/pnpm-store
            common/temp/install-run
          key: ${{ runner.os }}-rush-store-${{ hashFiles('common/config/subspaces/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-rush-store-main
            ${{ runner.os }}-rush-store

      - name: Install Dependencies
        if: steps.check_version.outputs.has_changes == 'true'
        run: |
          npm i -g @microsoft/rush@5.150.0
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
          node common/scripts/install-run-rush.js install

      - name: Run Release
        if: steps.check_version.outputs.has_changes == 'true'
        run: |
          git tag --points-at ${{ github.event.head_commit.id }}
          node common/scripts/install-run-rush.js release --commit ${{ github.event.head_commit.id }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Push Tags
        if: steps.check_version.outputs.has_changes == 'true'
        run: |
          git push origin --tags
